### ISSUE TITLE
Currency icon is one image, two staked images needed

### ISSUE THREAD

**Issue by dimkkv** [kamransaeed66/immuna#5]
![image](https://user-images.githubusercontent.com/107496196/187026163-6f19dbb7-dc10-4130-9a4d-16099e5b526e.png)

**Comment by kamransaeed66** [comment]
single image and the problem with "width" I fixed it u can check it

**Comment by dimkkv** [comment]
What have you fixed? 
![image](https://user-images.githubusercontent.com/107496196/187415151-ae043c0a-45be-4125-bce6-fbea07634550.png)

We still have one image.

**Comment by kamransaeed66** [comment]
hey 
yes we have one image at that time image was not clear now image is clear according to figma I download group image and its look nice that's why i used one image 
If you have any issue i can separate it but its will be issue on responsive

**Comment by kamransaeed66** [comment]
![image](https://user-images.githubusercontent.com/75786408/187423607-456ca784-cc30-4f1d-aa87-5592b2140660.png)
its 2 images wait let me check

**Comment by dimkkv** [comment]
![image](https://user-images.githubusercontent.com/107496196/187429081-eed4a2ef-940b-4039-b634-8093f6d844a0.png)

Mb, you didn't push the code?

**Comment by kamransaeed66** [comment]
hey 
now u can pull
