### ISSUE TITLE
Risk status is missing

### ISSUE THREAD

**Issue by dimkkv** [kamransaeed66/immuna#8]
From figma:
![image](https://user-images.githubusercontent.com/107496196/187415697-f718db2f-bb65-4ef1-ae5a-e33d3f02a9df.png)

I can't see this markup

**Comment by kamransaeed66** [comment]
![image](https://user-images.githubusercontent.com/75786408/187424196-6d0d4216-673c-48c0-931f-ce2f28b1fd5b.png)

hey 
If you click on the link "Click to View" the risk status is open  as I mention the Screenshort

**Comment by dimkkv** [comment]
Ok, thanks!

**Comment by kamransaeed66** [comment]
Welcome
